languageCode = "zh_CN"
title = "Air on G"
baseurl = "http://air.googol.im/"
Copyright = "All rights reserved - 2017"
caononifyurls = true

[params]
  disqusShortname = "air-g"
  description = "The Blog of Googol Lee"
  #cover = "images/cover.jpg"
  author = "Googol Lee"
  authorlocation = "Munich, Germany"
  authorwebsite = "http://air.googol.im"
  bio= "my bio"
  #logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "googollee"
  twitterName = "googollee"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "googollee"
