languageCode = "zh-CN"
title = "Air on G"
baseurl = "https://air.googol.im/"
copyright = "除非另有声明，本网站采用<a href='https://creativecommons.org/licenses/by-nd/3.0/cn/'>知识共享“署名-禁止演绎 3.0 中国大陆”许可协议</a>授权。"
caononifyurls = true
publishDir = "docs"
disqusShortname = "air-g"
theme = "casper"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"

[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/googollee"
weight = 100

[[menu.main]]
name = "Twitter timeline"
url = "https://twitter.com/googollee"
weight = 101

[params]
description = "The Blog of Googol Lee"
cover = "images/cover.jpg"
author = "Googol Lee"
authorlocation = "Munich, Germany"
authorwebsite = "https://air.googol.im"
bio= "多年生软件工程师，信仰开源"
#logo = "images/logo.png"
googleAnalyticsUserID = ""
# Optional RSS-Link, if not provided it defaults to the standard index.xml
# RSSLink = "http://feeds.feedburner.com/..."
githubName = "googollee"
twitterName = "googollee"
# facebookName = ""
# linkedinName = ""
# set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
hideHUGOSupport = false

[params.social]
twitter = "googollee"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
